### PR TITLE
Add test before and after date middleware

### PR DESCRIPTION
**Pull request by chemitaxis**
Add test for #43

### CODE REVIEW

**Comment by chemitaxis** [comment]
The checks is failing because I have added a test for this ;)

**Comment by chemitaxis** [comment]
Hi @diegohaz I have fixed the before and after test. The change is very simple. We are using querymen in production, please if you have time, check the commit, and upgrade the npm. Thank you so much for your work and time!

**Comment by diegohaz** [comment]
Nice. Thank you, @chemitaxis

**Comment by diegohaz** [comment]
Released `v2.1.2`

**Pull request merged**
