### PR TITLE
README.md updated to es6 features

### PR DESCRIPTION
**Pull request by jorgeluisrezende**
I had saw that topic on issue, and i made the updated..

### CODE REVIEW

**Comment by diegohaz** [comment]
Thank you, @jorgeluisrezende. 

I'll ask you just one thing: can we standardize spaces between brackets through the readme?

Let's use `import { foo } from 'foo'` and `{ foo: true }` instead of `{foo: true}`.

**Comment by jorgeluisrezende** [comment]
@diegohaz ok, i missed it, i will fix it

**Comment by jorgeluisrezende** [comment]
@diegohaz it is ok now, :smile:

**Comment by diegohaz** [comment]
Thanks. 😊

**Comment by drochag** [comment]
hey @jorgeluisrezende @diegohaz what about leaving `import { middleware as query }` as `import { middleware }`;

having a `query` as function and `query` in the inner scope might confuse ppl.

**Pull request merged**
