### PR TITLE
Fix cache problem

### PR DESCRIPTION
**Pull request by drochag**
@diegohaz I think this one is a better solution than #49 . However both of them (this one and #49) triggers the `pagination problem`.

Created both problems' tests so you everyone can be aware of the things to be solved.

cc. @chemitaxis

### CODE REVIEW

**Comment by chemitaxis** [comment]
Good job @DanMMX I can reproduce the both problems... I'm working on it... but, I don't know why I don't have this problem in production... like a say before, I'm using it like this:

```
const customSchema = {
  type: String,
  garment: String,
  brand: String,
  supplier: String,
  name: RegExp
}
```

`router.get('/', query(customSchema), index)`

I don't create a `new querymen.Schema`, and all is working fine.

**Comment by chemitaxis** [comment]
Hi @DanMMX, if you change the test in the cache and the pagination problems from:

```
let app = route(
      new querymen.Schema({
        title: RegExp
      })
    )
```


to:

```
let app = route(
      { title: RegExp }
    )
```

All the test is working... I think that reusable schemas are not working... Thanks.

**Comment by drochag** [comment]
Thanks a lot @chemitaxis 
So for anyone getting into this, a workaround for now is not to use a custom schema from the Schema constructor.

**Comment by chemitaxis** [comment]
Maybe @diegohaz can explain why it's happening... I have spent all the morning without success... I can't understand the benefits of create a reusable schema...

In our app in production we don't use reusable schemas, and is working fine...

**Comment by Wouter0100** [comment]
Thanks for mentioning, @DanMMX. Helped me fix a strange occurrence in my tests before things got to prod. :+1:

**Comment by wesias7** [comment]
+1

**Pull request closed without merging**
