### PR TITLE
Failing test for pagination with custom Schema

### PR DESCRIPTION
**Pull request by drochag**
Test to prove #50 

cc. @chemitaxis

### CODE REVIEW

**Comment by drochag** [comment]
@chemitaxis in this test you can check this

```

    request(app)
      .get('/tests')
      .query({limit: 2, page: 2})
      .expect(200)
      .end((err, res) => {
        if (err) throw err
        t.equal(res.body.length, 2, 'should respond with 2 items')
      })
```

won't work with a custom Schema. On my PR the cursor is being logged and you will see 

```
  Querymen middleware with custom Schema

    { skip: 0, limit: 2, sort: { createdAt: -1 } }
    { skip: 30, limit: 2, sort: { createdAt: -1 } }
    ✔ should respond with 2 items
    ✔ should equal same title
    ✔ should equal same title
```

even when having a limit of 2 and asking the 2nd page

**Comment by chemitaxis** [comment]
Thanks ;)

**Comment by chemitaxis** [comment]
Closed, just for the example...

**Comment by drochag** [comment]
Closing this PR. I've already created a second one with all the needed tests #52

**Pull request closed without merging**
